package model;

// class which holds boards used for testing garbage clearing
public final class GameGarbageBoards {
    static final String[][] GARBAGE_1 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null, null, null, null, null,  "I"},
        {null,  "J",  "J", null, null, null, null, null, null,  "I"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"}
    };

    static final String[][] GARBAGE_1_AFTER = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null,  "I", null, null, null,  "I"},
        {null, null,  "J", null, null,  "I", null, null, null,  "I"},
        {null,  "J",  "J", null, null,  "I", null, null, null,  "I"}
    };

    static final String[][] GARBAGE_2 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null, null, null, null, null,  "I"},
        {null,  "J",  "J", null, null, null, null, null, null,  "I"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"}
    };

    static final String[][] GARBAGE_2_AFTER = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null,  "I", null, null, null,  "I"},
        {null,  "J",  "J", null, null,  "I", null, null, null,  "I"}
    };

    static final String[][] GARBAGE_3 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null, null, null, null, null,  "I"},
        {null,  "J",  "J", null, null, null, null, null, null,  "I"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"}
    };

    static final String[][] GARBAGE_3_AFTER = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null, null, null, null, null,  "I"},
        {null,  "J",  "J", null, null,  "I", null, null, null,  "I"}
    };

    static final String[][] GARBAGE_4 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null, null, null, null, null,  "I"},
        {null,  "J",  "J", null, null, null, null, null, null,  "I"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"},
        { "G",  "G",  "G",  "G",  "G", null,  "G",  "G",  "G",  "G"}
    };

    static final String[][] GARBAGE_4_AFTER = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "S", null, null, null, null, null, null},
        {null, null,  "Z",  "S",  "S", null, null, null, null, null},
        {null,  "Z",  "Z", null,  "S", null, null, null, null, null},
        {null,  "Z",  "T",  "T",  "T", null, null, null, null,  "I"},
        {null, null,  "J",  "T", null, null, null, null, null,  "I"},
        {null, null,  "J", null, null, null, null, null, null,  "I"},
        {null,  "J",  "J", null, null, null, null, null, null,  "I"}
    };
}
