package model.pieces.boards;

// class which holds all of the board test states for T piece rotations
public final class PieceSTestBoards {
    /*
     * GENERAL
     */

    public static final String[][] FULL_0 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G",  "G", null, null, null},
        {null, null, null,  "G",  "G",  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] FULL_R = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null, null,  "G", null,  "G", null, null, null},
        {null, null, null, null, null,  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] FULL_2 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] FULL_L = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G", null, null, null, null, null, null},
        {null, null,  "G", null,  "G", null, null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    
    /*
     * CLOCKWISE ROTATION
     */

    // "0" -> "R"
    public static final String[][] CW_0_TO_R_1 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null, null,  "G",  "G", null,  "G", null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_0_TO_R_2 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G",  "G",  "G", null, null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null,  "G",  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_0_TO_R_3 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G", null, null, null, null, null, null},
        {null, null,  "G", null,  "G",  "G", null, null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_0_TO_R_4 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G",  "G", null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null, null,  "G", null,  "G", null, null, null},
        {null, null, null, null, null,  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_0_TO_R_5 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null,  "G", null,  "G", null, null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };

    // "R" -> "2"
    public static final String[][] CW_R_TO_2_1 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null,  "G", null,  "G",  "G", null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_R_TO_2_2 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null,  "G", null,  "G",  "G", null, null, null},
        {null, null, null,  "G", null, null, null,  "G", null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_R_TO_2_3 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null,  "G",  "G", null, null,  "G", null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_R_TO_2_4 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null,  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_R_TO_2_5 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null,  "G",  "G", null, null, null},
        {null, null, null, null,  "G", null, null,  "G", null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null, null,  "G", null,  "G", null, null, null},
        {null, null, null, null, null,  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };

    // "2" -> "L"
    public static final String[][] CW_2_TO_L_1 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G", null, null, null, null, null, null},
        {null, null,  "G", null,  "G",  "G", null, null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_2_TO_L_2 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null, null,  "G",  "G",  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_2_TO_L_3 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_2_TO_L_4 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_2_TO_L_5 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null, null, null,  "G", null,  "G", null, null, null},
        {null, null, null, null, null,  "G", null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };

    // "L" -> "0"
    public static final String[][] CW_L_TO_0_1 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G",  "G",  "G", null, null, null, null},
        {null, null,  "G", null, null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_L_TO_0_2 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null,  "G", null, null, null,  "G", null, null, null, null},
        {null, null,  "G",  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_L_TO_0_3 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G", null, null, null, null, null, null},
        {null, null,  "G", null,  "G", null, null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null,  "G", null, null, null,  "G", null, null, null, null},
        {null, null,  "G",  "G",  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_L_TO_0_4 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null,  "G",  "G", null, null, null, null},
        {null, null, null,  "G", null, null,  "G", null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null,  "G", null,  "G", null, null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    public static final String[][] CW_L_TO_0_5 = {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null,  "G",  "G", null, null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null,  "G", null, null,  "G", null, null, null, null, null},
        {null, null,  "G", null,  "G",  "G", null, null, null, null},
        {null, null,  "G", null, null,  "G", null, null, null, null},
        {null, null, null,  "G", null,  "G", null, null, null, null},
        {null, null, null, null,  "G", null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
    };
    
    /*
     * COUNTER-CLOCKWISE ROTATION
     */

    // "0" -> "L"
    public static final String[][] CCW_0_TO_L_1 = CW_L_TO_0_1;
    public static final String[][] CCW_0_TO_L_2 = CW_L_TO_0_2;
    public static final String[][] CCW_0_TO_L_3 = CW_L_TO_0_3;
    public static final String[][] CCW_0_TO_L_4 = CW_L_TO_0_4;
    public static final String[][] CCW_0_TO_L_5 = CW_L_TO_0_5;

    // "L" -> "2"
    public static final String[][] CCW_L_TO_2_1 = CW_2_TO_L_1;
    public static final String[][] CCW_L_TO_2_2 = CW_2_TO_L_2;
    public static final String[][] CCW_L_TO_2_3 = CW_2_TO_L_3;
    public static final String[][] CCW_L_TO_2_4 = CW_2_TO_L_4;
    public static final String[][] CCW_L_TO_2_5 = CW_2_TO_L_5;
    

    // "2" -> "R"
    public static final String[][] CCW_2_TO_R_1 = CW_R_TO_2_1;
    public static final String[][] CCW_2_TO_R_2 = CW_R_TO_2_2;
    public static final String[][] CCW_2_TO_R_3 = CW_R_TO_2_3;
    public static final String[][] CCW_2_TO_R_4 = CW_R_TO_2_4;
    public static final String[][] CCW_2_TO_R_5 = CW_R_TO_2_5;

    // "R" -> "0"
    public static final String[][] CCW_R_TO_0_1 = CW_0_TO_R_1;
    public static final String[][] CCW_R_TO_0_2 = CW_0_TO_R_2;
    public static final String[][] CCW_R_TO_0_3 = CW_0_TO_R_3;
    public static final String[][] CCW_R_TO_0_4 = CW_0_TO_R_4;
    public static final String[][] CCW_R_TO_0_5 = CW_0_TO_R_5;
}
